# Generated by Django 5.2.5 on 2025-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiempo_parking',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en minutos', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('otro', 'Otro')], default='carro', max_length=10),
        ),
    ]
