# Generated by Django 5.2.5 on 2025-08-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0002_cliente_fecha_entrada_cliente_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
