# Generated by Django 5.2.5 on 2025-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0003_cliente_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
