# Generated by Django 5.2.5 on 2025-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0004_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
