# Generated by Django 5.2.5 on 2025-08-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0005_cliente_barcode_image'),
    ]

    operations = [
    ]
