# Generated by Django 5.2.5 on 2025-08-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0006_auto_20250824_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='barcode_image',
        ),
    ]
