# Generated by Django 5.2.5 on 2025-08-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0009_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Moto', 'Moto'), ('Otro', 'Otro')], default='Auto', max_length=10),
        ),
    ]
