# Generated by Django 5.2.5 on 2025-08-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0010_alter_cliente_tipo_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_auto', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos por hora de estacionamiento para autos', max_digits=10, verbose_name='Costo por hora - Auto')),
                ('costo_moto', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos por hora de estacionamiento para motos', max_digits=10, verbose_name='Costo por hora - Moto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Costos',
                'verbose_name_plural': 'Configuración de Costos',
            },
        ),
    ]
