# Generated by Django 5.2.5 on 2025-08-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0011_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apartamento',
            field=models.CharField(blank=True, help_text='Número de apartamento', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='torre',
            field=models.CharField(blank=True, help_text='Torre del apartamento', max_length=10, null=True),
        ),
    ]
