# Generated by Django 5.2.5 on 2025-09-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0012_cliente_apartamento_cliente_torre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('torre', models.CharField(blank=True, help_text='Torre del apartamento que visita', max_length=10, null=True, verbose_name='Torre')),
                ('apartamento', models.CharField(blank=True, help_text='Número de apartamento que visita', max_length=10, null=True, verbose_name='Apartamento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
