# Generated by Django 5.2.5 on 2025-09-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0013_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='costo_auto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos por minuto de estacionamiento para autos', max_digits=10, verbose_name='Costo por minuto - Auto'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_moto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos por minuto de estacionamiento para motos', max_digits=10, verbose_name='Costo por minuto - Moto'),
        ),
    ]
