# Generated by Django 5.2.5 on 2025-09-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0014_alter_costo_costo_auto_alter_costo_costo_moto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaPlena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False, help_text='Activar/desactivar la tarifa plena con costo fijo', verbose_name='Tarifa plena activa')),
                ('costo_fijo_auto', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo fijo en pesos para autos cuando la tarifa plena está activa', max_digits=10, verbose_name='Costo fijo - Auto')),
                ('costo_fijo_moto', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo fijo en pesos para motos cuando la tarifa plena está activa', max_digits=10, verbose_name='Costo fijo - Moto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tarifa Plena',
                'verbose_name_plural': 'Tarifa Plena',
            },
        ),
    ]
