# Generated by Django 5.2.5 on 2025-09-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0015_tarifaplena'),
    ]

    operations = [
    ]
