# Generated by Django 5.2.5 on 2025-09-04 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0016_auto_20250904_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_recaudado', models.DecimalField(decimal_places=2, help_text='Total recaudado en el período', max_digits=12, verbose_name='Monto recaudado')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del período de recaudación', verbose_name='Fecha inicio del corte')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin del período de recaudación', verbose_name='Fecha fin del corte')),
                ('fecha_corte', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se realizó el corte', verbose_name='Fecha del corte')),
                ('numero_clientes', models.PositiveIntegerField(default=0, help_text='Cantidad de clientes atendidos en el período', verbose_name='Número de clientes')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el corte', null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el corte de recaudación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el corte')),
            ],
            options={
                'verbose_name': 'Recaudación',
                'verbose_name_plural': 'Recaudaciones',
                'ordering': ['-fecha_corte'],
            },
        ),
    ]
