# Generated by Django 5.2.5 on 2026-09-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0017_recaudacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/', verbose_name='Fotografía'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/', verbose_name='Fotografía'),
        ),
    ]
