# Generated by Django 5.2.5 on 2026-09-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0018_cliente_foto_visitante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='costo_otro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos por minuto de estacionamiento para otros vehiculos', max_digits=10, verbose_name='Costo por minuto - Otro'),
        ),
        migrations.AddField(
            model_name='tarifaplena',
            name='costo_fijo_otro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo fijo en pesos para otros vehiculos cuando la tarifa plena está activa', max_digits=10, verbose_name='Costo fijo - Otro'),
        ),
    ]
