# Generated by Django 5.2.5 on 2026-09-08 00:09

from decimal import Decimal

from django.db import migrations, models


def _tarifa_por_tipo(tarifas, prefijo, tipo_vehiculo):
    """Replica get_costo_por_tipo(): los modelos historicos no traen metodos."""
    tipo = (tipo_vehiculo or '').lower()
    if tipo == 'moto':
        return getattr(tarifas, f'{prefijo}_moto')
    if tipo == 'otro':
        return getattr(tarifas, f'{prefijo}_otro')
    # El resto cae en auto, igual que el respaldo del modelo.
    return getattr(tarifas, f'{prefijo}_auto')


def congelar_historial(apps, schema_editor):
    """Fija el cobro de las salidas ya registradas con las tarifas de hoy.

    No existe historial de tarifas, asi que este es el mejor valor disponible.
    Se hace una sola vez: a partir de aqui esos montos quedan inmunes a los
    cambios de precio, que era lo que descuadraba los cortes ya cerrados.
    """
    Cliente = apps.get_model('app_page', 'Cliente')
    Costo = apps.get_model('app_page', 'Costo')
    TarifaPlena = apps.get_model('app_page', 'TarifaPlena')

    costos = Costo.objects.filter(id=1).first()
    tarifa = TarifaPlena.objects.filter(id=1).first()
    if costos is None and tarifa is None:
        # Base nueva: no hay tarifas configuradas ni historial que congelar.
        return

    plena_activa = bool(tarifa and tarifa.activa)

    pendientes = []
    for cliente in Cliente.objects.filter(fecha_salida__isnull=False).iterator():
        if not cliente.fecha_entrada:
            continue

        if plena_activa:
            unitaria = _tarifa_por_tipo(tarifa, 'costo_fijo', cliente.tipo_vehiculo)
            monto = Decimal(unitaria)
        elif costos is not None:
            unitaria = _tarifa_por_tipo(costos, 'costo', cliente.tipo_vehiculo)
            minutos = int((cliente.fecha_salida - cliente.fecha_entrada).total_seconds() // 60)
            monto = Decimal(unitaria) * max(1, minutos)
        else:
            continue

        cliente.monto_cobrado = monto.quantize(Decimal('0.01'))
        cliente.tarifa_aplicada = unitaria
        cliente.cobrado_con_tarifa_plena = plena_activa
        pendientes.append(cliente)

    if pendientes:
        Cliente.objects.bulk_update(
            pendientes,
            ['monto_cobrado', 'tarifa_aplicada', 'cobrado_con_tarifa_plena'],
            batch_size=500,
        )


def descongelar_historial(apps, schema_editor):
    """Al revertir, los campos desaparecen igual; se limpian por prolijidad."""
    Cliente = apps.get_model('app_page', 'Cliente')
    Cliente.objects.update(monto_cobrado=None, tarifa_aplicada=None, cobrado_con_tarifa_plena=False)


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0019_costo_costo_otro_tarifaplena_costo_fijo_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cobrado_con_tarifa_plena',
            field=models.BooleanField(default=False, help_text='Modalidad vigente al registrar la salida', verbose_name='Cobrado con tarifa plena'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cobro congelado al registrar la salida; no lo alteran los cambios de tarifa posteriores', max_digits=12, null=True, verbose_name='Monto cobrado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tarifa_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa unitaria del cobro: por minuto, o el costo fijo si fue tarifa plena', max_digits=10, null=True, verbose_name='Tarifa aplicada'),
        ),
        migrations.RunPython(congelar_historial, descongelar_historial),
    ]
