# Generated by Django 5.2.5 on 2025-08-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la impresora')),
                ('printer_type', models.CharField(choices=[('USB', 'USB'), ('SERIAL', 'Serial'), ('NETWORK', 'Red')], default='USB', max_length=10, verbose_name='Tipo de conexión')),
                ('connection_string', models.CharField(help_text='Para USB: nombre de la impresora, Para Serial: puerto COM, Para Red: IP:Puerto', max_length=255, verbose_name='Cadena de conexión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('model', models.CharField(default='Epson M244A', max_length=50, verbose_name='Modelo')),
                ('paper_width', models.IntegerField(default=80, verbose_name='Ancho del papel (mm)')),
                ('chars_per_line', models.IntegerField(default=48, verbose_name='Caracteres por línea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresora',
                'verbose_name_plural': 'Configuraciones de Impresoras',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID del Cliente')),
                ('content_type', models.CharField(default='QR_CODE', max_length=20, verbose_name='Tipo de contenido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PRINTING', 'Imprimiendo'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_impresora.printerconfiguration')),
            ],
            options={
                'verbose_name': 'Trabajo de Impresión',
                'verbose_name_plural': 'Trabajos de Impresión',
                'ordering': ['-created_at'],
            },
        ),
    ]
