# Generated by Django 5.2.5 on 2025-08-25 15:48

from django.db import migrations


class Migration(migrations.Migration):
    """Migracion vacia a proposito.

    Esta migracion se genero por error como copia literal de 0001_initial:
    volvia a crear PrinterConfiguration y PrintJob, asi que `migrate` fallaba
    siempre con 'table app_impresora_printerconfiguration already exists' en
    cualquier base de datos nueva. Se dejan las operaciones vacias en lugar de
    borrar el fichero para no romper la dependencia de 0003 ni las bases de
    datos que ya la tienen registrada como aplicada.
    """

    dependencies = [
        ('app_impresora', '0001_initial'),
    ]

    operations = [
    ]
