# Generated by Django 5.2.5 on 2025-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_impresora', '0002_auto_20250825_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDesignConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración por defecto', max_length=100, verbose_name='Nombre de la configuración')),
                ('font', models.CharField(choices=[('courier', 'Courier New'), ('arial', 'Arial'), ('times', 'Times New Roman')], default='courier', max_length=20, verbose_name='Fuente')),
                ('font_size', models.IntegerField(default=12, verbose_name='Tamaño de fuente')),
                ('ticket_width', models.IntegerField(default=80, verbose_name='Ancho del ticket (mm)')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Mostrar logo/encabezado')),
                ('show_fecha', models.BooleanField(default=True, verbose_name='Mostrar fecha y hora')),
                ('show_qr', models.BooleanField(default=True, verbose_name='Mostrar código QR')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Mostrar pie de página')),
                ('header_text', models.TextField(default='SISTEMA DE PARKING\nControl de Acceso', help_text='Use \\n para saltos de línea', verbose_name='Texto del encabezado')),
                ('footer_text', models.TextField(default='Conserve este ticket\nGracias por su visita', help_text='Use \\n para saltos de línea', verbose_name='Texto del pie de página')),
                ('is_active', models.BooleanField(default=False, verbose_name='Configuración activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Diseño de Ticket',
                'verbose_name_plural': 'Configuraciones de Diseño de Tickets',
            },
        ),
    ]
